volumes:
    os_data:

services:
    opensearch:
        image: opensearchproject/opensearch:2.19.2
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - os_data:/usr/share/opensearch/data
        environment:
            - discovery.type=single-node
            - DISABLE_SECURITY_PLUGIN=true
            - DISABLE_INSTALL_DEMO_CONFIG=true
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
